name: Manage Railway Bot  # Nombre del Workflow

on:
  schedule:
    - cron: "0 7 * * *"  # Encender a las 10 AM UTC
    - cron: "0 20 * * *"  # Apagar a las 23 PM UTC

jobs:
  manage-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Railway CLI
        run: npm i -g @railway/cli

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Start/Stop bot
        run: |
          HOUR=$(date -u +%H)
          if [ "$HOUR" -eq "7" ]; then
            railway up
          elif [ "$HOUR" -eq "20" ]; then
            railway down
          fi
