name: Railway Bot Scheduler

on:
  schedule:
    - cron: "0 13 * * *"  # Encender a las 10:00 AM Argentina (13:00 UTC)
    - cron: "0 2 * * *"   # Apagar a las 23:00 PM Argentina (02:00 UTC)

jobs:
  manage-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
      
      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Start/Stop Railway Bot
        run: |
          HOUR=$(date -u +%H)
          if [ "$HOUR" -eq "13" ]; then
            railway up
          elif [ "$HOUR" -eq "2" ]; then
            railway down
          fi
